development:
  host: localhost
  database: geet_tmp_development

test:
  host: localhost
  database: geet_tmp_test

# set these environment variables on your prod server
production:
  host: localhost
  database: geet_tmp_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
